import React from 'react'
import Head from 'next/head'
import Pagina from "../components/products"

export default function Home() {
  return (
    <div>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Pagina />
    </div>
  )
}
